Enhancement/include exclude
nyxx-discord/glacier pull request #5
Opened 2021-08-31 17:38 UTC by HarryET

- Fix misc bugs
- Add base file include & exclude

2021-08-31 17:41 UTC, l7ssha requested changes

2021-08-31 17:41 UTC, l7ssha commented on cli/lib/commands/InitCommand.dart
> +      await file.writeAsString(fileData);
that could be moved to separate function to clean things out

2021-08-31 17:41 UTC, l7ssha commented on cli/lib/compiler/Compiler.dart
> +          true)) {
that should be moved maybe to variable because that if got really cluttered

2021-08-31 17:41 UTC, l7ssha commented on cli/lib/compiler/Compiler.dart
> +      copyFile.createSync(recursive: true);
why sync?

2021-08-31 17:41 UTC, l7ssha commented on cli/lib/compiler/Compiler.dart
> +              includePath.replaceFirst("/", "./").replaceFirst("\\", ".\\"))));
`replaceFirst("/", "./").replaceFirst("\\", ".\\")` stuff like that is used very often. Maybe creating util method will be cool?

2021-08-31 17:41 UTC, l7ssha commented on cli/lib/commands/GenerateCommand.dart
> +        config.destinationDirectory.replaceAll("./", "")));
should be moved to util methods since is used very often

2021-09-01 06:37 UTC, l7ssha requested changes

2021-09-01 06:37 UTC, l7ssha commented on cli/lib/commands/InitCommand.dart
> +        abbr: "b", defaultsTo: "nyxx-discord/glacier/templates/default");
maybe `template` option name and `t` for abbr would be better?

2021-09-01 06:37 UTC, l7ssha commented on cli/lib/commands/InitCommand.dart
> +    final repoPath = baseArg.split("/").sublist(2).join("/");
here is some magic. possible to siplify things? Or at least comment how it works?

2021-09-01 06:37 UTC, l7ssha commented on cli/lib/commands/InitCommand.dart
> +    }
that should be in util method probably

2021-09-12 07:55 UTC, HarryET commented on cli/lib/compiler/Compiler.dart
> +      copyFile.createSync(recursive: true);
Fixed

2021-09-12 18:07 UTC, l7ssha approved these changes

2021-09-12 18:07 UTC, merged